**Question No:1**

In [1]:
#Comparison of two arrays

import numpy as np

x = np.array([1,5,2,4,3])
y= np.array([1,2,3,4,5])

print(np.greater_equal(x,y))
print(np.greater(x,y))
print(np.less_equal(x,y))
print(np.less(x,y))



[ True  True False  True False]
[False  True False False False]
[ True False  True  True  True]
[False False  True False  True]


**Question No:2**

In [15]:
#Creating an array of 10 zeros,10 ones, 10 fives

x = np.zeros(10,dtype='int8')
y = np.ones(10,dtype='int8')
z = np.full((1,10),5)
print(x)
print(y)
print(z)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[[5 5 5 5 5 5 5 5 5 5]]


**Question No:3**

In [24]:
#sum of each value,each column,each rows in given array

array = np.array([[1,2,3],[1,2,3],[1,2,3]])

print("Sum of array is ",array.sum())

print("Sum of each rows in array is ",array.sum(axis=1))

print("Sum of each columns in array is ",array.sum(axis=0))


Sum of array is  18
Sum of each rows in array is  [6 6 6]
Sum of each columns in array is  [3 6 9]


**Question No:4**

In [28]:
#arithmetic operation element wise

x = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
y = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

#Addition
print(np.add(x,y))

#Subtraction

print(np.subtract(x,y))

#Multiplication

print(np.multiply(x,y))

#Division

print(np.divide(x,y))

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[ 1  4  9 16 25]
 [ 1  4  9 16 25]
 [ 1  4  9 16 25]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Question No:5**

In [47]:
#trigonometric sine, cosine and tangent array of angles given in degree

angles = np.array([0,30,45,60,90])

print(angles)

print()

print("sine values of given angles is ",np.sin(angles * np.pi / 180.))

print("cosine values of given angles is ",np.cos(angles * np.pi / 180.))

print("tangent values of given angles is ",np.tan(angles * np.pi / 180.))



[ 0 30 45 60 90]

sine values of given angles is  [0.         0.5        0.70710678 0.8660254  1.        ]
cosine values of given angles is  [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent values of given angles is  [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
