**Question No:1**

In [1]:
#Comparison of two arrays

import numpy as np

x = np.array([1,5,2,4,3])
y= np.array([1,2,3,4,5])

print(np.greater_equal(x,y))
print(np.greater(x,y))
print(np.less_equal(x,y))
print(np.less(x,y))



[ True  True False  True False]
[False  True False False False]
[ True False  True  True  True]
[False False  True False  True]


**Question No:2**

In [2]:
#Creating an array of 10 zeros,10 ones, 10 fives

x = np.zeros(10,dtype='int8')
y = np.ones(10,dtype='int8')
z = np.full((1,10),5)
print(x)
print(y)
print(z)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[[5 5 5 5 5 5 5 5 5 5]]


**Question No:3**

In [3]:
#sum of each value,each column,each rows in given array

array = np.array([[1,2,3],[1,2,3],[1,2,3]])

print("Sum of array is ",array.sum())

print("Sum of each rows in array is ",array.sum(axis=1))

print("Sum of each columns in array is ",array.sum(axis=0))


Sum of array is  18
Sum of each rows in array is  [6 6 6]
Sum of each columns in array is  [3 6 9]


**Question No:4**

In [4]:
#arithmetic operation element wise

x = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
y = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

#Addition
print(np.add(x,y))

#Subtraction

print(np.subtract(x,y))

#Multiplication

print(np.multiply(x,y))

#Division

print(np.divide(x,y))

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[ 1  4  9 16 25]
 [ 1  4  9 16 25]
 [ 1  4  9 16 25]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Question No:5**

In [5]:
#trigonometric sine, cosine and tangent array of angles given in degree

angles = np.array([0,30,45,60,90])

print(angles)

print()

print("sine values of given angles is ",np.sin(angles * np.pi / 180.))

print("cosine values of given angles is ",np.cos(angles * np.pi / 180.))

print("tangent values of given angles is ",np.tan(angles * np.pi / 180.))



[ 0 30 45 60 90]

sine values of given angles is  [0.         0.5        0.70710678 0.8660254  1.        ]
cosine values of given angles is  [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent values of given angles is  [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


**Question No:6**

In [6]:
#create and display dataframe from a specified dictionary with index labels

import pandas as pd
import numpy as np

dict1 = {'name':["sriram", "abirami", "suganesh", "jose"], 
        'degree': ["BE", "BE", "B.SC", np.nan], 
        'score':[95, 90, 80, 65]} 

df1 = pd.DataFrame(dict1,index=['one','two','three','four'])

df1

name degree  score
one      sriram     BE     95
two     abirami     BE     90
three  suganesh   B.SC     80
four       jose    NaN     65

**Question No:7**

In [7]:
#select name and score column in above dataframe

df1[['name','score']]

name  score
one      sriram     95
two     abirami     90
three  suganesh     80
four       jose     65

**Question No:8**

In [8]:
#Join two Dataframe

colg_details = {'name':["sriram", "abirami", "suganesh", "jose","sushma"],
      'colg_name':["GCE","GCE",np.nan,"GMC",12]}

index = ['a','b','c','d','e']

df2 = pd.DataFrame(colg_details,index)

df2

name colg_name
a    sriram       GCE
b   abirami       GCE
c  suganesh       NaN
d      jose       GMC
e    sushma        12

In [9]:
merged_details = df1.merge(df2,on='name',how='inner')

In [10]:
merged_details

name degree  score colg_name
0    sriram     BE     95       GCE
1   abirami     BE     90       GCE
2  suganesh   B.SC     80       NaN
3      jose    NaN     65       GMC

**Question No:9**

In [11]:
#detect missing in dataframe

merged_details.isnull().any()

name         False
degree        True
score        False
colg_name     True
dtype: bool

**Question No:10**

In [12]:
#create and display a one-dimensional array-like object containing an array of data

ser1 = pd.Series(["sriram",23,[93,90,89,98,93],450,"muhavooor"],index=["name","age","marks","score","address"])

ser1

name                     sriram
age                          23
marks      [93, 90, 89, 98, 93]
score                       450
address               muhavooor
dtype: object