In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets,metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [2]:
iris_X, iris_y = datasets.load_iris(return_X_y=True)

In [3]:
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test = iris_X[indices[-10:]]
iris_y_test = iris_y[indices[-10:]]

# using KNN

In [4]:
knn = KNeighborsClassifier(n_neighbors=5)

In [5]:
knn.fit(iris_X_train, iris_y_train)
KNeighborsClassifier()

KNeighborsClassifier()

In [6]:
predict=knn.predict(iris_X_test)

In [7]:
iris_y_test

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [8]:
print(metrics.accuracy_score(iris_y_test, predict))

0.9


In [9]:
matrix = metrics.confusion_matrix(iris_y_test,predict)

In [10]:
print(matrix)

[[4 0 0]
 [0 3 1]
 [0 0 2]]


# By logisticRegression

In [11]:
logisticRegr = LogisticRegression()

In [12]:
logisticRegr.fit(iris_X_train, iris_y_train)

/home/tzuser/ENTER/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
predictions = logisticRegr.predict(iris_X_test)

In [14]:
print(predictions)

[1 2 1 0 0 0 2 1 2 0]


In [15]:
score = logisticRegr.score(iris_X_test,iris_y_test)
print(score)

0.9


In [16]:
print(metrics.accuracy_score(iris_y_test, predictions))

0.9
